server:
  host: "localhost" # Defines the binding address <string>
  port: 8080 # Specifies the port <int> for the development server
#  https:
#    cert-path: "/path/to/cert.pem" # Path <string> to your TLS certificate
#    cert-key-path: "/path/to/key.pem" # Path <string> to TLS certificate key